#!/usr/bin/env bash

# sources:
# https://github.com/AlexTatiyants/dotfiles/blob/master/.brew
# 

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install GNU core utilities (those that come with OS X are outdated)
brew install coreutils
echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew install findutils
# Install Bash 4
brew install bash

# stanson toolchain
brew install ansible

# standard toolchain
brew install git python mosh wget

# Remove outdated versions from the cellar
brew cleanup
